---
- hosts: localhost
  tasks:
    - name: Installs nginx web server
      pacman: pkg=nginx state=installed
      notify:
        - start nginx

    - name: Upload default index.html for host
      copy: src=/root/website/Main.html dest=/usr/share/nginx/html/ mode=0644

  handlers:
    - name: start nginx
      service: name=nginx state=started
